// <auto-generated />
using System;
using Antitouch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antitouch.Migrations
{
    [DbContext(typeof(DiagramDbContext))]
    [Migration("20260427023617_M3_ShapeHierarchy_M5_ShapeFields")]
    partial class M3_ShapeHierarchy_M5_ShapeFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Antitouch.Models.DiagramCanvasModel", b =>
                {
                    b.Property<string>("CanvasID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AxisOrientationX")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AxisOrientationY")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AxisOrientationZ")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanvasName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CircleDefaultFill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CircleDefaultStroke")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CircleHandleActive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CircleHandleNormal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CircleHoverRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("CircleProtectRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("CoordinateSystemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagramID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GridColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("GridSpacingX")
                        .HasColumnType("REAL");

                    b.Property<double>("GridSpacingY")
                        .HasColumnType("REAL");

                    b.Property<bool>("GridVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HandleColorActive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HandleColorNormal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInfiniteX")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInfiniteY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInfiniteZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginDefinition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PanEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RectangleDefaultFill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RectangleDefaultStroke")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RectangleHandleActive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RectangleHandleNormal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RectangleHoverRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("RectangleProtectRatio")
                        .HasColumnType("REAL");

                    b.Property<bool>("ShowAxes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowOriginMarker")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ViewportCenterX")
                        .HasColumnType("REAL");

                    b.Property<double>("ViewportCenterY")
                        .HasColumnType("REAL");

                    b.Property<double>("ViewportHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("ViewportWidth")
                        .HasColumnType("REAL");

                    b.Property<bool>("ZoomEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ZoomScale")
                        .HasColumnType("REAL");

                    b.HasKey("CanvasID");

                    b.HasIndex("DiagramID")
                        .IsUnique();

                    b.ToTable("DiagramCanvases");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramModel", b =>
                {
                    b.Property<string>("DiagramID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanvasID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiagramVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DiagramID");

                    b.ToTable("Diagrams");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramShapeModel", b =>
                {
                    b.Property<string>("ShapeID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagramID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FillColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrokeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SvgIcon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<double>("WorldX")
                        .HasColumnType("REAL");

                    b.Property<double>("WorldY")
                        .HasColumnType("REAL");

                    b.HasKey("ShapeID");

                    b.HasIndex("DiagramID");

                    b.ToTable("DiagramShapes");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramShapeModel", b =>
                {
                    b.HasOne("Antitouch.Models.DiagramModel", "Diagram")
                        .WithMany("Shapes")
                        .HasForeignKey("DiagramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagram");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramModel", b =>
                {
                    b.Navigation("Shapes");
                });
#pragma warning restore 612, 618
        }
    }
}
