// <auto-generated />
using System;
using Antitouch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antitouch.Migrations
{
    [DbContext(typeof(DiagramDbContext))]
    [Migration("20260502223145_M7_Connections")]
    partial class M7_Connections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Antitouch.Models.ConnectionStyleDefaultModel", b =>
                {
                    b.Property<string>("ConnectionType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDashPattern")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLineColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultLineWidth")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThicknessName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionType");

                    b.ToTable("ConnectionStyleDefaults");
                });

            modelBuilder.Entity("Antitouch.Models.ConnectionTypeLookupModel", b =>
                {
                    b.Property<int>("LookupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationDeviceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDirectional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PossibleConnections")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDeviceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LookupID");

                    b.ToTable("ConnectionTypeLookups");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramCanvasModel", b =>
                {
                    b.Property<string>("CanvasID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AxisOrientationX")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AxisOrientationY")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AxisOrientationZ")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanvasName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoordinateSystemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagramID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GridColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("GridSpacingX")
                        .HasColumnType("REAL");

                    b.Property<double>("GridSpacingY")
                        .HasColumnType("REAL");

                    b.Property<bool>("GridVisible")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInfiniteX")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInfiniteY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInfiniteZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginDefinition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PanEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAxes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowOriginMarker")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ViewportCenterX")
                        .HasColumnType("REAL");

                    b.Property<double>("ViewportCenterY")
                        .HasColumnType("REAL");

                    b.Property<double>("ViewportHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("ViewportWidth")
                        .HasColumnType("REAL");

                    b.Property<bool>("ZoomEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ZoomScale")
                        .HasColumnType("REAL");

                    b.HasKey("CanvasID");

                    b.HasIndex("DiagramID")
                        .IsUnique();

                    b.ToTable("DiagramCanvases");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramConnectionDetailModel", b =>
                {
                    b.Property<string>("ConnectionDetailID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionRouteType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationJunctionPointID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationJunctionText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirectional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("LineWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("MiddleLineText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJunctionPointID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceJunctionText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThicknessName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionDetailID");

                    b.HasIndex("ConnectionID")
                        .IsUnique();

                    b.ToTable("DiagramConnectionDetails");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramConnectionModel", b =>
                {
                    b.Property<string>("ConnectionID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationItemID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationItemKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagramID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagramModelDiagramID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceItemID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceItemKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionID");

                    b.HasIndex("DiagramID");

                    b.HasIndex("DiagramModelDiagramID");

                    b.ToTable("DiagramConnections");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramModel", b =>
                {
                    b.Property<string>("DiagramID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanvasID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiagramVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DiagramID");

                    b.ToTable("Diagrams");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramShapeModel", b =>
                {
                    b.Property<string>("ShapeID")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagramID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FillColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillType")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("HoverPaddingColor")
                        .HasColumnType("TEXT");

                    b.Property<double?>("HoverPaddingRadiusRatio")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LineWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("ParentContainerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectionPaddingColor")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProtectionPaddingRadiusRatio")
                        .HasColumnType("REAL");

                    b.Property<double?>("Radius")
                        .HasColumnType("REAL");

                    b.Property<string>("StrokeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SvgIcon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.Property<double>("WorldX")
                        .HasColumnType("REAL");

                    b.Property<double>("WorldY")
                        .HasColumnType("REAL");

                    b.Property<int>("ZOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShapeID");

                    b.HasIndex("DiagramID");

                    b.ToTable("DiagramShapes");
                });

            modelBuilder.Entity("Antitouch.Models.ShapeHierarchyModel", b =>
                {
                    b.Property<int>("HierarchyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("HierarchyID");

                    b.ToTable("ShapeHierarchies");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramConnectionDetailModel", b =>
                {
                    b.HasOne("Antitouch.Models.DiagramConnectionModel", "Connection")
                        .WithOne("Detail")
                        .HasForeignKey("Antitouch.Models.DiagramConnectionDetailModel", "ConnectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramConnectionModel", b =>
                {
                    b.HasOne("Antitouch.Models.DiagramModel", "Diagram")
                        .WithMany()
                        .HasForeignKey("DiagramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Antitouch.Models.DiagramModel", null)
                        .WithMany("Connections")
                        .HasForeignKey("DiagramModelDiagramID");

                    b.Navigation("Diagram");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramShapeModel", b =>
                {
                    b.HasOne("Antitouch.Models.DiagramModel", "Diagram")
                        .WithMany("Shapes")
                        .HasForeignKey("DiagramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagram");
                });

            modelBuilder.Entity("Antitouch.Models.DiagramConnectionModel", b =>
                {
                    b.Navigation("Detail")
                        .IsRequired();
                });

            modelBuilder.Entity("Antitouch.Models.DiagramModel", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Shapes");
                });
#pragma warning restore 612, 618
        }
    }
}
